// Alimentos CONCRETOS de la lista de intercambio (U de A / ICBF 2025): que comer, en que cantidad, para
// una porcion de cada subgrupo. Es la mitad que el paciente se lleva a casa, y la referencia que el
// nutricionista consulta mientras arma el plan.
//
// PORTE FIEL, DATO PURO (2026-08-23). Transcripcion VERBATIM de INTER_TABLA_B de la entrega VIGENTE
// (docs/entregas/Gildardo responses/ATLAS_v8.html, 2026-08-19, la que Gildardo confirmo el 17 al corregir
// que "la vigente NO es la del 13"). 350 filas x 4 campos. NO se tecleo: se extrajo por script desde el
// HTML, porque a mano un gramaje mal copiado se lee como dato clinico y nadie lo notaria.
//
// CANDADO: inter-tabla-b.golden.test.ts compara las 350 filas ENTERAS contra el extracto de referencia,
// campo a campo, no una muestra. Ver ahi por que se hace con un deep-equal y no fila por fila.
//
// `med` (medida casera) VIAJA pero HOY NO SE MUESTRA: el v8 no la usa en ninguna de sus dos superficies
// (la tabla del profesional y la lista del paciente muestran solo "nombre (N g)"). Se porta el dato
// completo para no volver a extraerlo, y no se inventa una superficie que su archivo no tiene.

export type AlimentoConcreto = {
  sub: string; // subgrupo de INTER_TABLA_A al que equivale (clave de union)
  al: string; // nombre del alimento
  g: number; // gramos que hacen UNA porcion de intercambio
  med: string; // medida casera equivalente (portada, sin superficie hoy)
};

export const INTER_TABLA_B: AlimentoConcreto[] = [
  {sub:"Leche entera", al:"Kumis de leche entera", g:200, med:"1 vaso pequeño"},
  {sub:"Leche entera", al:"Leche de cabra cruda", g:200, med:"1 vaso pequeño"},
  {sub:"Leche entera", al:"Leche de vaca entera cruda", g:200, med:"1 vaso pequeño"},
  {sub:"Leche entera", al:"Leche de vaca entera en polvo", g:26, med:"3 cucharas soperas colmadas"},
  {sub:"Leche entera", al:"Leche de vaca entera pasteurizada", g:200, med:"1 vaso pequeño"},
  {sub:"Leche entera", al:"Yogurt regular de leche entera", g:200, med:"1 vaso pequeño"},
  {sub:"Leche semidescremada", al:"Avena líquida con leche de vaca descremada", g:250, med:"1 vaso pequeño"},
  {sub:"Leche semidescremada", al:"Bebida de Soya comercial", g:200, med:"1 vaso pequeño"},
  {sub:"Leche semidescremada", al:"Leche de vaca semidescremada en polvo", g:26, med:"3 cucharas soperas colmadas"},
  {sub:"Leche semidescremada", al:"Leche de vaca semidescremada pasteurizada (con o sin lactosa)", g:200, med:"1 vaso pequeño"},
  {sub:"Leche semidescremada", al:"Yogurt de leche entera - Yox", g:100, med:"1 tarro pequeño"},
  {sub:"Leche semidescremada", al:"Yogurt de leche entera cuchareable", g:140, med:"1 vaso pequeño"},
  {sub:"Leche descremada", al:"Leche de vaca descremada en polvo", g:21, med:"4 cucharas soperas colmadas"},
  {sub:"Leche descremada", al:"Leche de vaca descremada pasteurizada", g:200, med:"1 vaso pequeño"},
  {sub:"Leche descremada", al:"Yogurt de leche descremada", g:200, med:"1 vaso pequeño"},
  {sub:"Leche descremada", al:"Yogurt Griego natural", g:100, med:"1 vaso pequeño"},
  {sub:"Leche entera", al:"Avena con leche de vaca entera comercial", g:250, med:"1 vaso pequeño"},
  {sub:"Leche entera", al:"Kumis de leche entera azucarado", g:200, med:"1 vaso pequeño"},
  {sub:"Leche entera", al:"Leche de vaca entera chocolatada", g:200, med:"1 caja o vaso pequeño"},
  {sub:"Leche entera", al:"Yogurt de leche entera azucarado", g:200, med:"1 vaso pequeño"},
  {sub:"Sustitutos (embutidos, quesos, huevo)", al:"Butifarra", g:31, med:"1 unidad pequeña"},
  {sub:"Sustitutos (embutidos, quesos, huevo)", al:"Cuajada de leche de vaca", g:30, med:"1 tajada pequeña semigruesa"},
  {sub:"Sustitutos (embutidos, quesos, huevo)", al:"Huevo de gallina crudo", g:50, med:"1 unidad pequeña"},
  {sub:"Sustitutos (embutidos, quesos, huevo)", al:"Huevos de codorniz crudo", g:50, med:"5 unidades pequeñas"},
  {sub:"Sustitutos (embutidos, quesos, huevo)", al:"Jamón de Cerdo (97% libre de grasa y 25% reducido en sodio)", g:42, med:"2 tajadas"},
  {sub:"Sustitutos (embutidos, quesos, huevo)", al:"Jamón de Pavo", g:46, med:"2 tajadas"},
  {sub:"Sustitutos (embutidos, quesos, huevo)", al:"Morcilla", g:45, med:"1 trozo pequeño"},
  {sub:"Sustitutos (embutidos, quesos, huevo)", al:"Mortadela común", g:30, med:"2 tajadas"},
  {sub:"Sustitutos (embutidos, quesos, huevo)", al:"Pepperoni", g:16, med:"4 rodajas delgadas"},
  {sub:"Sustitutos (embutidos, quesos, huevo)", al:"Quesito", g:30, med:"1 tajada pequeña semigruesa"},
  {sub:"Sustitutos (embutidos, quesos, huevo)", al:"Queso Americano", g:24, med:"1 lonchita"},
  {sub:"Sustitutos (embutidos, quesos, huevo)", al:"Queso de búfala tipo mozzarella fresco graso de pasta hilada", g:30, med:"1 tajada gruesa"},
  {sub:"Sustitutos (embutidos, quesos, huevo)", al:"Queso Campesino (fresco semiduro, graso)", g:30, med:"1 tajada pequeña semigruesa"},
  {sub:"Sustitutos (embutidos, quesos, huevo)", al:"Queso Cheddar", g:20, med:"1 lonchita"},
  {sub:"Sustitutos (embutidos, quesos, huevo)", al:"Queso Costeño rallado", g:20, med:"2 cucharas soperas altas"},
  {sub:"Sustitutos (embutidos, quesos, huevo)", al:"Queso de Cabra", g:20, med:"1 tajada delgada"},
  {sub:"Sustitutos (embutidos, quesos, huevo)", al:"Queso fresco de pasta hilada, semiduro, semigraso (Finesse)", g:30, med:"2 lonchitas"},
  {sub:"Sustitutos (embutidos, quesos, huevo)", al:"Queso fresco semiduro graso", g:30, med:"1 tajada pequeña semigruesa"},
  {sub:"Sustitutos (embutidos, quesos, huevo)", al:"Queso Gouda", g:20, med:"1 tajada delgada"},
  {sub:"Sustitutos (embutidos, quesos, huevo)", al:"Queso mozzarella de leche entera de vaca semiduro, semigraso", g:34, med:"2 lonchitas"},
  {sub:"Sustitutos (embutidos, quesos, huevo)", al:"Queso Parmesano rallado", g:14, med:"2 cucharas soperas colmadas"},
  {sub:"Sustitutos (embutidos, quesos, huevo)", al:"Queso Ricotta (de leche semidescremada)", g:50, med:"2 cucharas soperas altas"},
  {sub:"Sustitutos (embutidos, quesos, huevo)", al:"Queso sabana (Edam)", g:22, med:"1 tajada delgada"},
  {sub:"Sustitutos (embutidos, quesos, huevo)", al:"Queso Tipo Pera", g:36, med:"1 unidad pequeña"},
  {sub:"Sustitutos (embutidos, quesos, huevo)", al:"Salami", g:25, med:"5 rodajas delgadas medianas"},
  {sub:"Sustitutos (embutidos, quesos, huevo)", al:"Salchicha tradicional", g:25, med:"1 unidad mediana"},
  {sub:"Sustitutos (embutidos, quesos, huevo)", al:"Salchicha vegetariana", g:37, med:"1 unidad mediana"},
  {sub:"Sustitutos (embutidos, quesos, huevo)", al:"Salchichón cervecero", g:34, med:"1 tajada gruesa"},
  {sub:"Sustitutos (embutidos, quesos, huevo)", al:"Salchichón de pollo", g:40, med:"1 trozo mediano"},
  {sub:"Carnes magras", al:"Atún enlatado en agua, sólidos", g:120, med:"1 lata"},
  {sub:"Carnes magras", al:"Carne de cabra o chivo", g:100, med:"1/5 libra"},
  {sub:"Carnes magras", al:"Carne de cerdo lomo o cañón magro", g:100, med:"1/5 libra"},
  {sub:"Carnes magras", al:"Carne de conejo todos los cortes", g:100, med:"1/5 libra"},
  {sub:"Carnes magras", al:"Carne de cordero diferentes cortes grasa menor 10%", g:100, med:"1/5 libra"},
  {sub:"Carnes magras", al:"Carne de cuy", g:100, med:"1/5 libra"},
  {sub:"Carnes magras", al:"Carne de res todos los cortes magra", g:100, med:"1/5 libra"},
  {sub:"Carnes magras", al:"Carne de ternera diferentes cortes magra", g:100, med:"1/5 libra"},
  {sub:"Carnes magras", al:"Chuleta de cerdo magra", g:100, med:"1/5 libra"},
  {sub:"Carnes magras", al:"Contramuslo de pollo, carne sin piel", g:86, med:"1 unidad mediana"},
  {sub:"Carnes magras", al:"Muslo de pollo, carne sin piel", g:75, med:"1 unidad mediana"},
  {sub:"Carnes magras", al:"Pargo especies mezcladas", g:100, med:"1 trozo mediano"},
  {sub:"Carnes magras", al:"Pavo todas las carnes sin piel", g:100, med:"1/5 libra"},
  {sub:"Carnes magras", al:"Pechuga de pollo, carne sin piel", g:80, med:"1/4 unidad grande"},
  {sub:"Carnes magras", al:"Proteína de soya texturizada hidratada", g:60, med:"2 cucharas soperas colmadas"},
  {sub:"Carnes magras", al:"Proteína de trigo texturizada hidratada", g:75, med:"3 cucharas soperas colmadas"},
  {sub:"Carnes magras", al:"Salmón rosado, crudo", g:73, med:"1 trozo pequeño"},
  {sub:"Carnes magras", al:"Trucha arcoíris", g:81, med:"1/2 unidad mediana"},
  {sub:"Carnes altas en lípidos", al:"Alas de pollo carne y piel", g:84, med:"2 unidades medianas"},
  {sub:"Carnes altas en lípidos", al:"Bagre carne y piel", g:76, med:"1 medallón grueso"},
  {sub:"Carnes altas en lípidos", al:"Callo o panza", g:100, med:"1/5 libra"},
  {sub:"Carnes altas en lípidos", al:"Camarón especies mezcladas", g:73, med:"6 unidades grandes"},
  {sub:"Carnes altas en lípidos", al:"Contramuslo de pollo sin hueso y con piel", g:105, med:"1 unidad mediana"},
  {sub:"Carnes altas en lípidos", al:"Hígado de pollo", g:72, med:"2 unidades medianas"},
  {sub:"Carnes altas en lípidos", al:"Hígado de res", g:100, med:"1/5 libra"},
  {sub:"Carnes altas en lípidos", al:"Langostino especies mezcladas", g:95, med:"6 unidades medianas"},
  {sub:"Carnes altas en lípidos", al:"Lengua de res", g:100, med:"1/5 libra"},
  {sub:"Carnes altas en lípidos", al:"Sardina enlatada en salsa de tomate", g:100, med:"2 unidades medianas"},
  {sub:"Leguminosas", al:"Arveja seca cocida", g:157, med:"1 cucharón colmado"},
  {sub:"Leguminosas", al:"Fríjol blanquillo con guiso**", g:110, med:"1 cucharón colmado"},
  {sub:"Leguminosas", al:"Fríjol bola roja con plátano verde*", g:120, med:"1 cucharón colmado"},
  {sub:"Leguminosas", al:"Fríjol cabecita negra con guiso**", g:130, med:"1 cucharón colmado"},
  {sub:"Leguminosas", al:"Fríjol caraota con guiso**", g:130, med:"1 cucharón colmado"},
  {sub:"Leguminosas", al:"Fríjol cargamanto blanco con plátano verde*", g:110, med:"1 cucharón colmado"},
  {sub:"Leguminosas", al:"Fríjol cargamanto rosado con plátano verde*", g:110, med:"1 cucharón colmado"},
  {sub:"Leguminosas", al:"Fríjol nima con guiso**", g:130, med:"1 cucharón colmado"},
  {sub:"Leguminosas", al:"Fríjol verde con plátano verde*", g:100, med:"1 cucharón colmado"},
  {sub:"Leguminosas", al:"Fríjol zaragoza con guiso**", g:100, med:"1 cucharón colmado"},
  {sub:"Leguminosas", al:"Garbanzo con guiso**", g:100, med:"1 cucharón colmado"},
  {sub:"Leguminosas", al:"Lenteja con guiso**", g:130, med:"1 cucharón colmado"},
  {sub:"Leguminosas", al:"Soya con guiso**", g:90, med:"1 cucharón colmado"},
  {sub:"Leguminosas", al:"Fríjol blanquillo con guiso**", g:60, med:"1/2 cucharón"},
  {sub:"Leguminosas", al:"Fríjol bola roja con plátano verde*", g:65, med:"1/2 cucharón"},
  {sub:"Leguminosas", al:"Fríjol cabecita negra con guiso**", g:70, med:"1/2 cucharón"},
  {sub:"Leguminosas", al:"Fríjol caraota con guiso**", g:70, med:"1/2 cucharón"},
  {sub:"Leguminosas", al:"Fríjol cargamanto blanco con plátano verde*", g:60, med:"1/2 cucharón"},
  {sub:"Leguminosas", al:"Fríjol cargamanto rosado con plátano verde*", g:60, med:"1/2 cucharón"},
  {sub:"Leguminosas", al:"Fríjol nima con guiso**", g:70, med:"1/2 cucharón"},
  {sub:"Leguminosas", al:"Fríjol verde con plátano verde*", g:60, med:"1/2 cucharón"},
  {sub:"Leguminosas", al:"Fríjol zaragoza con guiso**", g:50, med:"1/2 cucharón"},
  {sub:"Leguminosas", al:"Garbanzo con guiso**", g:50, med:"1/2 cucharón"},
  {sub:"Leguminosas", al:"Lenteja con guiso**", g:70, med:"1/2 cucharón"},
  {sub:"Leguminosas", al:"Soya con guiso**", g:50, med:"1/2 cucharón"},
  {sub:"Cereales", al:"Almojábana", g:31, med:"1 unidad pequeña"},
  {sub:"Cereales", al:"Arepa delgada de maíz blanco trillado", g:56, med:"1 unidad pequeña"},
  {sub:"Cereales", al:"Arepa redonda de maíz blanco trillado", g:52, med:"1 unidad grande"},
  {sub:"Cereales", al:"Arroz blanco, cocido", g:80, med:"6 cucharas soperas colmadas"},
  {sub:"Cereales", al:"Arroz integral, cocido", g:81, med:"8 cucharas soperas colmadas"},
  {sub:"Cereales", al:"Arroz parbolizado cocido", g:75, med:"5 cucharas soperas colmadas"},
  {sub:"Cereales", al:"Avena en hojuelas fortificada", g:24, med:"4 cucharas soperas colmadas"},
  {sub:"Cereales", al:"Cebada perlada cocida", g:72, med:"5 cucharas soperas colmadas"},
  {sub:"Cereales", al:"Choco Krispis", g:23, med:"2/3 pocillo chocolatero"},
  {sub:"Cereales", al:"Corn Flakes", g:25, med:"2/3 pocillo chocolatero"},
  {sub:"Cereales", al:"Cuchuco de cebada", g:27, med:"4 cucharas soperas colmadas"},
  {sub:"Cereales", al:"Espaguetis de arroz, hidratados", g:75, med:"2/3 pocillo chocolatero"},
  {sub:"Cereales", al:"Espaguetis de trigo, cocidos", g:65, med:"2/3 pocillo chocolatero"},
  {sub:"Cereales", al:"Froot Loops", g:20, med:"2/3 pocillo chocolatero"},
  {sub:"Cereales", al:"Galletas Saltinas", g:24, med:"3 tablas"},
  {sub:"Cereales", al:"Harina de arroz blanco", g:25, med:"2 cucharas soperas colmadas"},
  {sub:"Cereales", al:"Harina de maíz blanco trillado", g:25, med:"2 cucharas soperas rasas"},
  {sub:"Cereales", al:"Harina de trigo enriquecida", g:25, med:"4 cucharas soperas rasas"},
  {sub:"Cereales", al:"Macarrones, cocidos", g:64, med:"2/3 pocillo chocolatero"},
  {sub:"Cereales", al:"Maicena (almidón de maíz)", g:25, med:"4 cucharas soperas rasas"},
  {sub:"Cereales", al:"Maíz pira, crudo", g:27, med:"1 cuchara sopera colmada"},
  {sub:"Cereales", al:"Maíz tierno o choclo, amarillo enlatado", g:110, med:"8 cucharas soperas colmadas"},
  {sub:"Cereales", al:"Maíz tostado comercial", g:21, med:"3 cucharas soperas colmadas"},
  {sub:"Cereales", al:"Mazamorra Antioqueña (maíz cocido)", g:100, med:"5 cucharas soperas altas"},
  {sub:"Cereales", al:"Palitos o palitroques", g:22, med:"2 unidades"},
  {sub:"Cereales", al:"Pan blanco", g:22, med:"1 tajada delgada"},
  {sub:"Cereales", al:"Pan centeno", g:35, med:"1 tajada mediana"},
  {sub:"Cereales", al:"Pan de salvado de avena", g:38, med:"1 tajada mediana"},
  {sub:"Cereales", al:"Pan integral", g:32, med:"1 tajada mediana"},
  {sub:"Cereales", al:"Pan pita o árabe", g:25, med:"1/2 unidad pequeña"},
  {sub:"Cereales", al:"Pancake (mezcla preparada con leche entera)", g:40, med:"1 unidad mediana"},
  {sub:"Cereales", al:"Pandequeso", g:28, med:"1 unidad pequeña"},
  {sub:"Cereales", al:"Pandeyuca", g:20, med:"2 unidades medianas"},
  {sub:"Cereales", al:"Pasta corta cocida", g:65, med:"2/3 pocillo chocolatero"},
  {sub:"Cereales", al:"Seba Seba", g:24, med:"3 unidades medianas"},
  {sub:"Cereales", al:"Taco vacío", g:26, med:"2 unidades medianas"},
  {sub:"Cereales", al:"Tortilla de maíz", g:30, med:"1 unidad pequeña"},
  {sub:"Cereales", al:"Tostada o calado", g:32, med:"1 unidad mediana"},
  {sub:"Cereales", al:"Zucaritas", g:25, med:"2/3 pocillo chocolatero"},
  {sub:"Raíces, tubérculos y plátanos", al:"Arracacha", g:96, med:"1 trozo pequeño"},
  {sub:"Raíces, tubérculos y plátanos", al:"Batata", g:100, med:"1 trozo pequeño"},
  {sub:"Raíces, tubérculos y plátanos", al:"Chuguas u ollucos", g:155, med:"9 unidades grandes"},
  {sub:"Raíces, tubérculos y plátanos", al:"Cubios", g:155, med:"2 unidades grandes"},
  {sub:"Raíces, tubérculos y plátanos", al:"Harina de plátano", g:24, med:"2 cucharas soperas colmadas"},
  {sub:"Raíces, tubérculos y plátanos", al:"Ñame", g:78, med:"1 trozo pequeño"},
  {sub:"Raíces, tubérculos y plátanos", al:"Papa común", g:83, med:"1 unidad mediana"},
  {sub:"Raíces, tubérculos y plátanos", al:"Papa criolla", g:108, med:"3 unidades medianas"},
  {sub:"Raíces, tubérculos y plátanos", al:"Plátano colí o guineo", g:88, med:"1 unidad mediana"},
  {sub:"Raíces, tubérculos y plátanos", al:"Plátano hartón maduro", g:66, med:"1/4 unidad mediana"},
  {sub:"Raíces, tubérculos y plátanos", al:"Plátano verde", g:78, med:"1/2 unidad mediana"},
  {sub:"Raíces, tubérculos y plátanos", al:"Yuca blanca", g:62, med:"1 trozo mediano"},
  {sub:"Poliinsaturadas", al:"Aceite de ajonjolí", g:5, med:"1 cuchara tintera"},
  {sub:"Poliinsaturadas", al:"Aceite de girasol", g:5, med:"1 cuchara sopera"},
  {sub:"Poliinsaturadas", al:"Aceite de maíz", g:5, med:"1 cuchara sopera"},
  {sub:"Poliinsaturadas", al:"Aceite de soya", g:5, med:"1 cuchara sopera"},
  {sub:"Poliinsaturadas", al:"Mayonesa regular comercial", g:6, med:"1 cuchara dulcera rasa"},
  {sub:"Poliinsaturadas", al:"Salsa Ranch", g:11, med:"1 cuchara sopera colmada"},
  {sub:"Poliinsaturadas", al:"Salsa Tártara", g:12, med:"1 cuchara sopera colmada"},
  {sub:"Poliinsaturadas", al:"Vinagreta con grasa (Aderezos)", g:10, med:"1 cuchara sopera"},
  {sub:"Monoinsaturadas", al:"Aceite de aguacate", g:5, med:"1 cuchara sopera"},
  {sub:"Monoinsaturadas", al:"Aceite de canola", g:5, med:"2 cucharas soperas"},
  {sub:"Monoinsaturadas", al:"Aceite de oliva", g:5, med:"1 cuchara sopera"},
  {sub:"Monoinsaturadas", al:"Aceitunas deshuesadas", g:40, med:"12 unidades medianas"},
  {sub:"Monoinsaturadas", al:"Aguacate común", g:30, med:"1/8 unidad mediana"},
  {sub:"Monoinsaturadas", al:"Aguacate Hass", g:30, med:"1/4 unidad mediana"},
  {sub:"Monoinsaturadas", al:"Mantequilla de Maní", g:8, med:"1 cuchara dulcera colmada"},
  {sub:"Monoinsaturadas", al:"Margarinas suaves, sin sal", g:6, med:"2 cucharas dulceras rasas"},
  {sub:"Monoinsaturadas", al:"Salsa Pesto", g:10, med:"1 cuchara sopera colmada"},
  {sub:"Saturadas", al:"Aceite de palma", g:5, med:"1 cuchara sopera"},
  {sub:"Saturadas", al:"Crema agria (Sour cream)", g:26, med:"2 cucharas soperas colmadas"},
  {sub:"Saturadas", al:"Crema de leche líquida, espesa entera", g:13, med:"1 cuchara sopera colmada"},
  {sub:"Saturadas", al:"Manteca de cerdo", g:5, med:"1 cuchara dulcera rasa"},
  {sub:"Saturadas", al:"Mantequilla sin sal", g:5, med:"1 cuchara dulcera rasa"},
  {sub:"Saturadas", al:"Queso crema", g:12, med:"1 cuchara sopera rasa"},
  {sub:"Reducidos en grasa", al:"Crema de leche Light", g:27, med:"4 cucharas soperas colmadas"},
  {sub:"Reducidos en grasa", al:"Margarina line (reducida 25%)", g:10, med:"1 cuchara sopera rasa"},
  {sub:"Reducidos en grasa", al:"Mayonesa Light", g:22, med:"2 cucharas soperas altas"},
  {sub:"Reducidos en grasa", al:"Queso crema light", g:27, med:"1 cuchara sopera alta"},
  {sub:"Reducidos en grasa", al:"Salsa de queso Cheddar", g:26, med:"1 cuchara sopera alta"},
  {sub:"Frutas", al:"Banano común", g:65, med:"1 unidad pequeña"},
  {sub:"Frutas", al:"Borojó", g:54, med:"2/3 pocillo chocolatero"},
  {sub:"Frutas", al:"Chirimoya", g:92, med:"1/2 unidad mediana"},
  {sub:"Frutas", al:"Chontaduro", g:27, med:"1 unidad pequeña"},
  {sub:"Frutas", al:"Ciruela claudia", g:108, med:"2 unidades pequeñas"},
  {sub:"Frutas", al:"Ciruela común", g:60, med:"12 unidades medianas"},
  {sub:"Frutas", al:"Curuba", g:200, med:"6 unidades grandes"},
  {sub:"Frutas", al:"Feijoa", g:117, med:"3 unidades pequeñas"},
  {sub:"Frutas", al:"Fresas", g:161, med:"9 unidades medianas"},
  {sub:"Frutas", al:"Granadilla", g:100, med:"1 unidad grande"},
  {sub:"Frutas", al:"Guanábana", g:100, med:"4 cucharas soperas colmadas"},
  {sub:"Frutas", al:"Guayaba criolla", g:105, med:"1 unidad mediana"},
  {sub:"Frutas", al:"Guayaba manzana", g:169, med:"1 unidad mediana"},
  {sub:"Frutas", al:"Higo", g:113, med:"2 unidades pequeñas"},
  {sub:"Frutas", al:"Kiwi", g:82, med:"1 unidad mediana"},
  {sub:"Frutas", al:"Lulo", g:196, med:"2 unidades pequeñas"},
  {sub:"Frutas", al:"Lulo jugo", g:200, med:"1 vaso mediano"},
  {sub:"Frutas", al:"Mango", g:112, med:"1 unidad pequeña"},
  {sub:"Frutas", al:"Manzana con cáscara toda variedad", g:112, med:"1 unidad pequeña"},
  {sub:"Frutas", al:"Maracuyá", g:66, med:"1 unidad mediana"},
  {sub:"Frutas", al:"Melón", g:126, med:"1 tajada delgada"},
  {sub:"Frutas", al:"Mora", g:96, med:"1/2 pocillo chocolatero"},
  {sub:"Frutas", al:"Murrapo", g:49, med:"1 unidad mediana"},
  {sub:"Frutas", al:"Naranja", g:147, med:"1 unidad pequeña"},
  {sub:"Frutas", al:"Naranja orlando", g:144, med:"1 unidad pequeña"},
  {sub:"Frutas", al:"Naranja tangelo", g:131, med:"1 unidad pequeña"},
  {sub:"Frutas", al:"Naranja valencia", g:126, med:"1 unidad pequeña"},
  {sub:"Frutas", al:"Papaya", g:128, med:"1 trozo mediano"},
  {sub:"Frutas", al:"Papayuela", g:308, med:"1 unidad mediana"},
  {sub:"Frutas", al:"Pera", g:85, med:"1/2 unidad mediana"},
  {sub:"Frutas", al:"Piña manzana", g:110, med:"1 tajada delgada"},
  {sub:"Frutas", al:"Pitahaya", g:110, med:"1 unidad mediana"},
  {sub:"Frutas", al:"Sandía Baby", g:156, med:"1/4 unidad pequeña"},
  {sub:"Frutas", al:"Tomate árbol común", g:174, med:"2 unidades medianas"},
  {sub:"Frutas", al:"Tomate árbol rojo", g:167, med:"2 unidades medianas"},
  {sub:"Frutas", al:"Uchuva", g:68, med:"17 unidades"},
  {sub:"Frutas", al:"Zapote sin semilla", g:118, med:"2 unidades pequeñas"},
  {sub:"Azúcares y dulces", al:"Arequipe", g:27, med:"1 cuchara sopera colmada"},
  {sub:"Azúcares y dulces", al:"Azúcar blanca granulada", g:26, med:"2 cucharas soperas colmadas"},
  {sub:"Azúcares y dulces", al:"Bebida achocolatada instantánea con azúcar", g:20, med:"2 cucharas soperas altas"},
  {sub:"Azúcares y dulces", al:"Bebida de fruta azucarada", g:200, med:"1 caja pequeña"},
  {sub:"Azúcares y dulces", al:"Bebida de té instantáneo con azúcar", g:22, med:"2 cucharas soperas colmadas"},
  {sub:"Azúcares y dulces", al:"Bebida de té líquida", g:300, med:"1 botella comercial"},
  {sub:"Azúcares y dulces", al:"Bebida malta", g:200, med:"1 vaso mediano"},
  {sub:"Azúcares y dulces", al:"Bocadillo de guayaba", g:30, med:"1 tajada delgada"},
  {sub:"Azúcares y dulces", al:"Brevas en almíbar drenadas", g:47, med:"2 unidades medianas"},
  {sub:"Azúcares y dulces", al:"Caramelos", g:24, med:"6 unidades pequeñas"},
  {sub:"Azúcares y dulces", al:"Cerezas en almíbar", g:90, med:"1 frasco pequeño"},
  {sub:"Azúcares y dulces", al:"Chocolatina blanca comercial", g:15, med:"1 unidad pequeña"},
  {sub:"Azúcares y dulces", al:"Chocolatina de leche", g:12, med:"1 unidad pequeña"},
  {sub:"Azúcares y dulces", al:"Ciruelas pasas", g:41, med:"8 unidades medianas"},
  {sub:"Azúcares y dulces", al:"Cocada de panela", g:25, med:"1 unidad mediana"},
  {sub:"Azúcares y dulces", al:"Coctel de frutas", g:157, med:"3/4 pocillo chocolatero"},
  {sub:"Azúcares y dulces", al:"Confites duros", g:22, med:"5 unidades"},
  {sub:"Azúcares y dulces", al:"Cucas", g:19, med:"1 unidad pequeña"},
  {sub:"Azúcares y dulces", al:"Durazno enlatado", g:173, med:"3 mitades medianas"},
  {sub:"Azúcares y dulces", al:"Gaseosa", g:200, med:"1 vaso mediano"},
  {sub:"Azúcares y dulces", al:"Gelatina con azúcar preparada", g:160, med:"1 pocillo chocolatero"},
  {sub:"Azúcares y dulces", al:"Gelatina de pata", g:23, med:"1 unidad mediana"},
  {sub:"Azúcares y dulces", al:"Gomita tradicional", g:24, med:"5 unidades pequeñas"},
  {sub:"Azúcares y dulces", al:"Helado de agua", g:200, med:"1 unidad comercial"},
  {sub:"Azúcares y dulces", al:"Helado de vainilla", g:45, med:"1 bola pequeña"},
  {sub:"Azúcares y dulces", al:"Jarabe de maple", g:37, med:"4 cucharas soperas"},
  {sub:"Azúcares y dulces", al:"Leche condensada", g:28, med:"2 cucharas soperas"},
  {sub:"Azúcares y dulces", al:"Masmelos", g:30, med:"6 unidades pequeñas"},
  {sub:"Azúcares y dulces", al:"Mermelada", g:30, med:"2 cucharas soperas colmadas"},
  {sub:"Azúcares y dulces", al:"Mermelada light", g:60, med:"4 cucharas soperas colmadas"},
  {sub:"Azúcares y dulces", al:"Miel de abejas", g:21, med:"1 cuchara sopera"},
  {sub:"Azúcares y dulces", al:"Panela en polvo", g:26, med:"2 cucharas soperas colmadas"},
  {sub:"Azúcares y dulces", al:"Panelita de arequipe", g:23, med:"1 unidad pequeña"},
  {sub:"Azúcares y dulces", al:"Piña enlatada", g:172, med:"6 rodajas pequeñas"},
  {sub:"Azúcares y dulces", al:"Ponqué cubierto de chocolate comercial", g:21, med:"1 unidad mini"},
  {sub:"Azúcares y dulces", al:"Ponqué mediano tradicional", g:25, med:"1 trozo pequeño"},
  {sub:"Azúcares y dulces", al:"Postre gelatina-leche", g:65, med:"1 trozo mediano"},
  {sub:"Verduras y hortalizas", al:"Arveja verde", g:42, med:"3 cucharas soperas colmadas"},
  {sub:"Verduras y hortalizas", al:"Auyama", g:68, med:"1 trozo mediano"},
  {sub:"Verduras y hortalizas", al:"Baby carrots", g:52, med:"10 unidades medianas"},
  {sub:"Verduras y hortalizas", al:"Brócoli crudo sin hojas, ni tallos", g:89, med:"1 pocillo chocolatero"},
  {sub:"Verduras y hortalizas", al:"Cebolla blanca cruda", g:74, med:"1 unidad pequeña"},
  {sub:"Verduras y hortalizas", al:"Cebolla puerro", g:50, med:"1 tallo grueso"},
  {sub:"Verduras y hortalizas", al:"Cebolla roja", g:66, med:"1 unidad pequeña"},
  {sub:"Verduras y hortalizas", al:"Champiñón tajado", g:100, med:"1 pocillo chocolatero alto"},
  {sub:"Verduras y hortalizas", al:"Champiñones", g:93, med:"1/2 pocillo chocolatero"},
  {sub:"Verduras y hortalizas", al:"Champiñones enlatados", g:83, med:"1/2 pocillo chocolatero"},
  {sub:"Verduras y hortalizas", al:"Chócolo desgranado", g:30, med:"3 cucharas soperas colmadas"},
  {sub:"Verduras y hortalizas", al:"Cidrayota", g:177, med:"1/2 unidad mediana"},
  {sub:"Verduras y hortalizas", al:"Coliflor", g:86, med:"3 gajos pequeños"},
  {sub:"Verduras y hortalizas", al:"Espárragos enlatados", g:105, med:"19 tallos delgados"},
  {sub:"Verduras y hortalizas", al:"Habichuela", g:81, med:"1/2 pocillo chocolatero"},
  {sub:"Verduras y hortalizas", al:"Habichuelas enlatadas", g:100, med:"3/4 pocillo chocolatero"},
  {sub:"Verduras y hortalizas", al:"Palmitos enlatados", g:71, med:"1/2 pocillo chocolatero"},
  {sub:"Verduras y hortalizas", al:"Pepinillos agridulces", g:21, med:"6 unidades pequeñas"},
  {sub:"Verduras y hortalizas", al:"Pimentón rojo", g:111, med:"1 unidad mediana"},
  {sub:"Verduras y hortalizas", al:"Rábano con cáscara", g:125, med:"7 unidades medianas"},
  {sub:"Verduras y hortalizas", al:"Remolacha, cocida", g:57, med:"1/2 unidad pequeña"},
  {sub:"Verduras y hortalizas", al:"Tomate chonto", g:118, med:"1 unidad pequeña"},
  {sub:"Verduras y hortalizas", al:"Tomate larga vida", g:132, med:"1 unidad pequeña"},
  {sub:"Verduras y hortalizas", al:"Tomate riñón", g:104, med:"1/2 unidad grande"},
  {sub:"Verduras y hortalizas", al:"Tomate rojo maduro enlatado", g:105, med:"1/2 pocillo chocolatero"},
  {sub:"Verduras y hortalizas", al:"Zanahoria", g:58, med:"1/2 pocillo chocolatero"},
  {sub:"Nueces", al:"Almendras tostadas sin sal", g:9, med:"3 unidades medianas"},
  {sub:"Nueces", al:"Avellanas tostadas sin sal", g:7, med:"5 unidades medianas"},
  {sub:"Nueces", al:"Coco deshidratado", g:9, med:"2 cucharas soperas colmadas"},
  {sub:"Nueces", al:"Coco fresco rallado", g:14, med:"2 cucharas soperas altas"},
  {sub:"Nueces", al:"Macadamia tostada sin sal", g:6, med:"3 unidades medianas"},
  {sub:"Nueces", al:"Maní sin sal", g:10, med:"1 cuchara sopera colmada"},
  {sub:"Nueces", al:"Marañón tostado sin sal", g:10, med:"1 cuchara sopera colmada"},
  {sub:"Nueces", al:"Mezcla de nueces", g:11, med:"1 cuchara sopera colmada"},
  {sub:"Nueces", al:"Nuez del Brasil", g:8, med:"2 unidades medianas"},
  {sub:"Nueces", al:"Nuez del nogal", g:8, med:"2 unidades medianas"},
  {sub:"Nueces", al:"Pacanas tostadas sin sal", g:8, med:"3 unidades medianas"},
  {sub:"Semillas", al:"Linaza entera", g:36, med:"3 cucharas soperas colmadas"},
  {sub:"Semillas", al:"Linaza pulverizada", g:12, med:"2 cucharas soperas colmadas"},
  {sub:"Semillas", al:"Semillas de ajonjolí tostadas", g:10, med:"1 cuchara sopera colmada"},
  {sub:"Semillas", al:"Semillas de amapola", g:11, med:"1 cuchara sopera colmada"},
  {sub:"Semillas", al:"Semillas de calabaza", g:10, med:"1 cuchara sopera colmada"},
  {sub:"Semillas", al:"Semillas de girasol descortezadas", g:10, med:"1 cuchara sopera colmada"},
  {sub:"Semillas", al:"Semillas de soya", g:10, med:"1 cuchara sopera colmada"},
  {sub:"Mecato", al:"3D triángulos", g:30, med:"1 paquete pequeño"},
  {sub:"Mecato", al:"Boli cheetos", g:26, med:"1 paquete pequeño"},
  {sub:"Mecato", al:"Brownie mama-ia arequipe", g:100, med:"1 unidad"},
  {sub:"Mecato", al:"Cheese tris", g:52, med:"1 paquete pequeño"},
  {sub:"Mecato", al:"Choclitos limón", g:29, med:"1 paquete pequeño"},
  {sub:"Mecato", al:"Choco poff", g:15, med:"1 paquete pequeño"},
  {sub:"Mecato", al:"Colombineta", g:20, med:"1 unidad"},
  {sub:"Mecato", al:"Crispetas comerciales de caramelo", g:24, med:"1 paquete mediano"},
  {sub:"Mecato", al:"Crispetas comerciales de mantequilla", g:11, med:"1 paquete mediano"},
  {sub:"Mecato", al:"Crispetas comerciales de queso", g:13, med:"1 paquete mediano"},
  {sub:"Mecato", al:"Doritos arepitas", g:30, med:"1 paquete pequeño"},
  {sub:"Mecato", al:"Doritos mega queso", g:30, med:"1 paquete pequeño"},
  {sub:"Mecato", al:"Mini cheetos", g:10, med:"1 paquete pequeño"},
  {sub:"Mecato", al:"Mini chips chocolate", g:35, med:"1 paquete pequeño"},
  {sub:"Mecato", al:"Mini recreo", g:40, med:"1 paquete pequeño"},
  {sub:"Mecato", al:"Palitos margarita", g:39, med:"1 paquete pequeño"},
  {sub:"Mecato", al:"Papas fritas criollas", g:25, med:"1 paquete pequeño"},
  {sub:"Mecato", al:"Papitas limón", g:25, med:"1 paquete pequeño"},
  {sub:"Mecato", al:"Papitas pollo", g:30, med:"1 paquete pequeño"},
  {sub:"Mecato", al:"Platanitos maduros", g:35, med:"1 paquete pequeño"},
  {sub:"Mecato", al:"Plátanos limón", g:28, med:"1 paquete pequeño"},
  {sub:"Mecato", al:"Rosquitas", g:18, med:"1 paquete pequeño"},
  {sub:"Mecato", al:"Sapito", g:14, med:"1 unidad"},
  {sub:"Mecato", al:"Tosti arepa", g:30, med:"1 paquete pequeño"},
  {sub:"Mecato", al:"Yogueta", g:20, med:"1 unidad"},
  {sub:"Mecato", al:"Yupis", g:16, med:"1 paquete pequeño"},
  {sub:"Bebidas alcohólicas", al:"Aguardiente", g:35, med:"1 copa"},
  {sub:"Bebidas alcohólicas", al:"Cerveza 3,6 gr %", g:300, med:"1 botella"},
  {sub:"Bebidas alcohólicas", al:"Cerveza baja caloría 3,2 gr %", g:300, med:"1 botella"},
  {sub:"Bebidas alcohólicas", al:"Chicha 4%", g:200, med:"1 vaso pequeno"},
  {sub:"Bebidas alcohólicas", al:"Crema de menta 29,8%", g:70, med:"1 copa"},
  {sub:"Bebidas alcohólicas", al:"Daiquiri 23,2 gr %", g:70, med:"1 copa"},
  {sub:"Bebidas alcohólicas", al:"Ginebra 37,9 gr %", g:35, med:"1 copa"},
  {sub:"Bebidas alcohólicas", al:"Guarapo 3 %", g:200, med:"1 vaso pequeno"},
  {sub:"Bebidas alcohólicas", al:"Licor de café 21,75 %", g:70, med:"1 copa"},
  {sub:"Bebidas alcohólicas", al:"Manhattan 36,9 %", g:70, med:"1 copa"},
  {sub:"Bebidas alcohólicas", al:"Martini 38,4 %", g:90, med:"1 copa"},
  {sub:"Bebidas alcohólicas", al:"Piña colada 12,3 %", g:150, med:"1 copa"},
  {sub:"Bebidas alcohólicas", al:"Ron 33,4 gr %", g:35, med:"1 copa"},
  {sub:"Bebidas alcohólicas", al:"Tom Collins (ginebra 18,9%)", g:200, med:"1 vaso pequeno"},
  {sub:"Bebidas alcohólicas", al:"Vino blanco 9,3 gr %", g:90, med:"1 copa"},
  {sub:"Bebidas alcohólicas", al:"Vino rosado 9,3 gr %", g:90, med:"1 copa"},
  {sub:"Bebidas alcohólicas", al:"Vino tinto 9,3 gr %", g:90, med:"1 copa"},
  {sub:"Bebidas alcohólicas", al:"Vodka 33,4 gr %", g:35, med:"1 copa"},
  {sub:"Bebidas alcohólicas", al:"Whisky 36 gr %", g:35, med:"1 copa"},
  {sub:"Bebidas no alcohólicas", al:"Avena instantánea saborizada", g:25, med:"2 cucharas soperas colmadas"},
  {sub:"Bebidas no alcohólicas", al:"Café instantáneo descafeinado en polvo", g:3, med:"1 cuchara dulcera"},
  {sub:"Bebidas no alcohólicas", al:"Café instantáneo en polvo", g:3, med:"1 cuchara dulcera"},
  {sub:"Bebidas no alcohólicas", al:"Chocolate amargo", g:8, med:"1 pastilla"},
  {sub:"Bebidas no alcohólicas", al:"Chocolate con azúcar", g:25, med:"1 pastilla"},
  {sub:"Bebidas no alcohólicas", al:"Chocolate granulado con panela", g:31, med:"2 cucharas soperas colmadas"}
];

// Alimentos de un subgrupo, en el orden en que vienen de la tabla (el v8 no reordena).
export function alimentosDe(sub: string): AlimentoConcreto[] {
  return INTER_TABLA_B.filter((a) => a.sub === sub);
}
