// Ciclo de menus colombianos de 21 dias que PRECARGA la grilla del menu semanal (seccion F del v8).
//
// PORTE FIEL, DATO PURO (2026-08-23). Transcripcion VERBATIM de CICLO_MENU_21 de la entrega VIGENTE
// (docs/entregas/Gildardo responses/ATLAS_v8.html, 2026-08-19). Extraido por script, no tecleado.
// Candado: ciclo-menu.golden.test.ts.
//
// NO es prescripcion: es una PRECARGA editable. El profesional cambia cualquier celda y lo que se guarda
// es lo que el dejo. En el v8 el ciclo es tambien el fallback cuando la IA no responde.
//
// EL CICLO TRAE CINCO TIEMPOS Y ATLAS MANEJA SEIS. Falta `merienda`: el ciclo de Gildardo no la cubre.
// Su columna queda VACIA y la UI dice POR QUE (un blanco sin explicacion se lee como fallo; un aviso le
// dice al profesional que la llene el). Inventarle una merienda seria contenido clinico NUESTRO. Si algun
// dia Gildardo la agrega al ciclo, esa columna se llena sola: el codigo lee `dia[tiempo]` sin lista fija.

export type DiaDelCiclo = {
  desayuno: string;
  mediasOnces: string;
  almuerzo: string;
  algo: string;
  cena: string;
};

export const CICLO_MENU_21: DiaDelCiclo[] = [
  { desayuno:'Jugo de mango mezclado con leche (1 vaso), 1 pan blanco (1 pan) y 1 huevo revuelto', mediasOnces:'1 banano mediano con galletas de sal', almuerzo:'Sopa de lentejas con ahuyama, arroz de fideo, pechuga guisada (1 presa), ensalada de repollo con tomate y zanahoria, papa salteada (1 porción mediana) y jugo de tamarindo', algo:'Yogur (1 pocillo), 3 galletas wafer, bocadillo (1 unidad) y pera (1 unidad)', cena:'Arepa de maíz asada (1 unidad) con queso en porción (1 tajada) y aguapanela con canela' },
  { desayuno:'Chocolate mezclado con leche (1 vaso), 3 galletas de sal con mermelada (1 cucharada) y queso en porción (1 tajada)', mediasOnces:'1 naranja mediana y 1 porción de ponqué', almuerzo:'Sopa mixta con arvejas, arroz de ajo, carne goulash (1 porción, tamaño de la palma), ensalada de remolacha zanahoria y cebolla, patacón (1 porción mediana) y jugo de maracuyá', algo:'Kumis (1 pocillo), 3 tostadas con panelita de leche (1 unidad) y patilla (1 tajada)', cena:'Papa cocida (1 unidad mediana), tortilla de huevo con verduras (2 cucharadas) y jugo de tomate de árbol' },
  { desayuno:'Yogur (1 pocillo), puré de papa (1 unidad mediana) con mantequilla y 1 huevo cocido', mediasOnces:'1 pera mediana con 3 galletas ducales', almuerzo:'Crema de ahuyama, pasta guisada (1 pocillo), carne molida con verduras (1 porción, tamaño de la palma), pan blanco (1 tajada) y jugo de guayaba', algo:'Batido de avena con leche, galleta punto rojo (1 unidad) y manzana (1 unidad)', cena:'Tostadas (3 tostadas) con mermelada (1 cucharada), queso en porción (1 tajada) y jugo de fruta de cosecha' },
  { desayuno:'Kumis (1 pocillo) y arepa de maíz asada (1 unidad) con queso (1 tajada) y mantequilla', mediasOnces:'1 papaya mediana y 3 galletas de leche', almuerzo:'Sopa de garbanzos con ahuyama, arroz de cebolla, pollo asado (1 presa), ensalada de zanahoria pepino y tomate, papa chorreada (1 porción mediana) y jugo de piña', algo:'Jugo de mango mezclado con leche (1 vaso), galletas de sal y chocolatina (1 unidad) y banano (1 unidad)', cena:'Pan blanco (1 pan), 1 huevo frito y jugo de guayaba' },
  { desayuno:'Aguapanela con leche (1 vaso), 3 tostadas y queso en porción rallado (3 cucharadas)', mediasOnces:'1 porción de mango mediana y 3 galletas wafer', almuerzo:'Crema de zanahoria, arroz blanco, hígado guisado en cuadritos (1 porción, tamaño de la palma), ensalada de lechuga tomate y cebolla, tajada madura (1 porción mediana) y jugo de melón', algo:'Yogur (1 pocillo), 3 galletas ducales y mandarina (1 unidad)', cena:'Plátano amarillo (1 unidad mediana) con mantequilla, 1 huevo cocido y jugo de patilla' },
  { desayuno:'Batido de avena con leche, pan blanco (1 pan) con mantequilla y tortilla de huevo', mediasOnces:'1 manzana mediana y 3 galletas punto rojo', almuerzo:'Sopa de habichuelas y lentejas, arroz de ajo, carne desmechada (1 porción, tamaño de la palma), ensalada cocida de zanahoria remolacha y cebolla, papas a la francesa (1 porción mediana) y jugo de tomate de árbol', algo:'Kumis (1 pocillo), 3 galletas de queso y dulce de guayaba (1 unidad) y pera (1 unidad)', cena:'Pasta grande (1 pocillo) con verduras (2 cucharadas) y queso en trozos (1 tajada) y jugo de mango' },
  { desayuno:'Jugo de mora mezclado con leche (1 vaso), 2 tortillas de maíz (1 unidad cada una) y queso en porción (1 tajada)', mediasOnces:'1 porción de pera mediana y ponqué (1 tajada)', almuerzo:'Sopa de verduras, arroz blanco, pechuga en salsa criolla (1 presa), ensalada de pepino tomate y cebolla, croquetas de yuca (1 porción mediana) y jugo de guayaba', algo:'Yogur (1 pocillo), 3 galletas de mantequilla y chocolatina (1 unidad) y banano (1 unidad)', cena:'Puré de papa (1 unidad mediana) con mantequilla y verduras (2 cucharadas), 1 huevo revuelto y jugo de tamarindo' },
  { desayuno:'Chocolate mezclado con leche (1 vaso), 3 tostadas y 1 huevo cocido', mediasOnces:'1 porción de piña mediana y 3 galletas ducales', almuerzo:'Crema de ahuyama, arroz de cebolla, patas guisadas (1 porción, tamaño de la palma), ensalada de repollo zanahoria y cebolla, plátano maduro frito (1 porción mediana) y jugo de maracuyá', algo:'Batido de avena con leche, galletas de queso (3 galletas) y bocadillo (1 unidad) y melón (1 tajada)', cena:'Croquetas de yuca (1 unidad mediana) con queso en porción (1 tajada) y jugo de fruta de cosecha' },
  { desayuno:'Kumis (1 pocillo), 2 buñuelos de harina de trigo (1 unidad cada uno) y queso rallado (3 cucharadas)', mediasOnces:'1 porción de melón mediana y 3 galletas de leche', almuerzo:'Crema de zanahoria, pasta guisada (1 pocillo), pechuga con verduras (1 presa), moneditas de plátano verde (1 porción mediana) y jugo de tamarindo', algo:'Yogur (1 pocillo), 3 tostadas y gelatina grande (1 porción) y papaya (1 tajada)', cena:'2 tortillas de maíz (1 unidad cada una), 1 huevo revuelto con verduras (2 cucharadas) y jugo de tomate de árbol' },
  { desayuno:'Jugo de mango mezclado con leche (1 vaso), arepa dulce de maíz (1 unidad) y 1 huevo frito', mediasOnces:'1 banano mediano y 3 galletas de mantequilla', almuerzo:'Sopa mixta con garbanzos, arroz de fideo, albóndigas con verduras (1 porción, tamaño de la palma), plátano maduro (1 porción mediana) y jugo de tomate de árbol', algo:'Kumis (1 pocillo), 3 galletas wafer y chocolatina (1 unidad) y naranja (1 unidad)', cena:'Hojaldre (1 unidad), queso en porción (1 tajada) y jugo de guayaba' },
  { desayuno:'Jugo de mora mezclado con leche (1 vaso), 3 galletas de sal con mantequilla y queso en porción (1 tajada)', mediasOnces:'1 mandarina mediana y 3 galletas punto rojo', almuerzo:'Sopa de lentejas con ahuyama, arroz con espinaca, 1 huevo frito, ensalada de lechuga pimentón y zanahoria, papas salteadas (1 porción mediana) y jugo de patilla', algo:'Yogur (1 pocillo), 3 tostadas y dulce de guayaba (1 unidad) y manzana (1 unidad)', cena:'Arepa de maíz (1 tajada) con torta pequeña de carne molida (1 porción, tamaño de la palma) y jugo de tomate de árbol' },
  { desayuno:'Batido de avena con leche, pan blanco (1 pan) con mermelada (1 cucharada) y 1 huevo revuelto', mediasOnces:'3 tostadas con mango en cuadritos (1 tajada)', almuerzo:'Sopa mixta con arvejas, arroz de ajo, carne goulash (1 porción, tamaño de la palma), ensalada de pepino zanahoria y cebolla, papas a la francesa (1 porción mediana) y jugo de maracuyá', algo:'Kumis (1 pocillo), 3 galletas de sal y ponqué (1 unidad) y mango (1 unidad)', cena:'Puré de papa (1 unidad mediana) con mantequilla y verduras (2 cucharadas) con queso rallado (3 cucharadas) y jugo de melón' },
  { desayuno:'Yogur (1 pocillo), 2 buñuelos de harina de trigo (1 unidad cada uno) y queso rallado (3 cucharadas)', mediasOnces:'1 pera mediana y 3 galletas ducales', almuerzo:'Crema de verduras, pasta guisada (1 pocillo), carne desmechada con verduras (1 porción, tamaño de la palma), pan tajado (1 tajada) y jugo de guayaba', algo:'Batido de avena con leche, galleta de leche y chocolatina (1 unidad) y piña (1 unidad)', cena:'Tostadas (3 tostadas) con mermelada (1 cucharada), tortilla de huevo y jugo de fruta de cosecha' },
  { desayuno:'Kumis (1 pocillo), 2 tortillas de maíz (1 unidad cada una) con mantequilla y 1 huevo cocido', mediasOnces:'1 banano mediano y 3 galletas de queso', almuerzo:'Sopa de garbanzos con ahuyama, arroz de cebolla, pollo frito (1 presa), ensalada de zanahoria pepino y tomate, papa chorreada (1 porción mediana) y jugo de mora', algo:'Yogur (1 pocillo), 3 galletas punto rojo y bocadillo (1 unidad) y melón (1 tajada)', cena:'Puré de plátano amarillo (1 unidad mediana) con mantequilla y queso rallado (3 cucharadas) y jugo de patilla' },
  { desayuno:'Aguapanela con leche (1 vaso), 3 tostadas y queso en porción (1 tajada)', mediasOnces:'1 porción de manzana mediana y 3 galletas wafer', almuerzo:'Crema de zanahoria, arroz blanco, carne asada (1 porción, tamaño de la palma), ensalada de lechuga tomate y cebolla, moneditas de plátano verde (1 porción mediana) y jugo de melón', algo:'Kumis (1 pocillo), 3 tostadas y panelita de leche (1 unidad) y mandarina (1 unidad)', cena:'Yuca cocida (1 unidad mediana) y 1 huevo revuelto con verduras (2 cucharadas) y jugo de piña' },
  { desayuno:'Aguapanela con leche (1 vaso), 2 arepas dulces de maíz pequeñas (1 unidad cada una) y 1 huevo frito', mediasOnces:'1 mandarina mediana y 3 galletas de sal', almuerzo:'Crema de ahuyama, arroz de fideo, pollo agridulce (1 presa), ensalada cocida de habichuela zanahoria y remolacha, papas chorreadas (1 porción mediana) y jugo de tamarindo', algo:'Yogur (1 pocillo), 3 galletas wafer y bocadillo (1 unidad) y naranja (1 unidad)', cena:'Patacón (1 unidad mediana) con queso (1 tajada) y aguapanela con limón' },
  { desayuno:'Jugo de mora mezclado con leche (1 vaso), pan blanco (1 pan) con mantequilla y queso rallado (3 cucharadas)', mediasOnces:'1 porción de melón mediano y ponqué (1 tajada)', almuerzo:'Sopa mixta con arvejas, arroz de ajo, carne guisada (1 porción, tamaño de la palma), ensalada de pimentón repollo y zanahoria, plátano maduro frito (1 porción mediana) y jugo de maracuyá', algo:'Batido de avena con leche, 3 galletas de leche y dulce de guayaba (1 unidad) y pera (1 unidad)', cena:'Papa cocida (1 unidad mediana) con mantequilla, 1 huevo cocido y jugo de piña' },
  { desayuno:'Chocolate mezclado con leche (1 vaso), 3 tostadas y tortilla de huevo', mediasOnces:'1 porción de pera mediana y 3 galletas ducales', almuerzo:'Sopa de lentejas con espinaca, arroz de cebolla, patas guisadas (1 porción, tamaño de la palma), ensalada de lechuga zanahoria y tomate, papas a la francesa (1 porción mediana) y jugo de patilla', algo:'Kumis (1 pocillo), 3 galletas de mantequilla y gelatina grande (1 porción) y manzana (1 unidad)', cena:'2 buñuelos de maíz (1 unidad cada uno) con queso en porción (1 tajada) y jugo de mango' },
  { desayuno:'Kumis (1 pocillo) y arepa de maíz asada (1 unidad) con queso rallado (3 cucharadas) y mantequilla', mediasOnces:'1 porción de manzana mediana y 3 galletas wafer', almuerzo:'Sopa de garbanzos con ahuyama, arroz blanco, pechuga agridulce con verduras (1 presa), moneditas de plátano verde (1 porción mediana) y jugo de guayaba', algo:'Yogur (1 pocillo), 3 tostadas y panelita de leche (1 unidad) y melón (1 tajada)', cena:'Rebanada de pan blanco (1 pan), 1 huevo frito y jugo de guayaba' },
  { desayuno:'Aguapanela con leche (1 vaso), 3 galletas de sal con mermelada (1 cucharada) y pollo desmechado (1 presa)', mediasOnces:'1 porción con papaya (1 tajada) y 3 galletas punto rojo', almuerzo:'Sopa de verduras, arroz de pimentón, albóndigas con verduras (1 porción, tamaño de la palma), puré de papa (1 porción mediana) y jugo de tomate de árbol', algo:'Batido de avena con leche, galletas de queso y chocolatina (1 unidad) y mango (1 unidad)', cena:'Plátano amarillo cocido (1 unidad mediana) con mantequilla, 1 huevo revuelto con verduras (2 cucharadas) y jugo de patilla' },
  { desayuno:'Yogur (1 pocillo), 2 hojaldres (1 unidad cada una) y 1 huevo revuelto', mediasOnces:'1 porción de pera mediana y 3 galletas de leche', almuerzo:'Crema de zanahoria, arroz de ajo, pechuga en salsa criolla (1 presa), ensalada de lechuga tomate y cebolla, tajada de plátano madura (1 porción mediana) y jugo de melón', algo:'Kumis (1 pocillo), galleta punto rojo (1 unidad) y cobadillo (1 unidad) y piña (1 unidad)', cena:'2 tortillas pequeñas de maíz (1 unidad cada una) con queso en porción (1 tajada) y jugo de mora' }
];

export const DIAS_DEL_CICLO = CICLO_MENU_21.length; // 21

// Menu del dia `n` de la semana (0-6) contando desde `diaInicio`, dando la vuelta al ciclo. Es la rotacion
// del v8 (`CICLO_MENU_21[(diaInicio+i) % 21]`), con el arranque como parametro en vez de aleatorio: ver
// la nota de la semilla en el writer. PURO.
export function diaDelCiclo(diaInicio: number, offset: number): DiaDelCiclo {
  const base = ((Math.trunc(diaInicio) % DIAS_DEL_CICLO) + DIAS_DEL_CICLO) % DIAS_DEL_CICLO;
  return CICLO_MENU_21[(base + offset) % DIAS_DEL_CICLO];
}

// Dia de arranque DERIVADO del tratamiento, para la precarga ANTES del primer guardado. Determinista (el
// mismo tratamiento da siempre la misma semana, sin parpadeo al recargar) y distinto entre evaluaciones del
// mismo paciente, para no repetirle la semana en el seguimiento. Al guardar, el arranque se PERSISTE y esta
// funcion deja de gobernar ese plan: por eso cambiarla no mueve ningun menu ya guardado.
//
// No es criptografia ni ciencia clinica: solo necesita ser estable y repartir.
export function diaInicioDerivado(treatmentId: string): number {
  let h = 0;
  for (let i = 0; i < treatmentId.length; i++) h = (h * 31 + treatmentId.charCodeAt(i)) >>> 0;
  return h % DIAS_DEL_CICLO;
}
