// AUTO-GENERADO desde ATLAS_v7.html (función importarComposicion COMPLETA, 94 campos)
// + validado contra export real BiodyConnect android v1.2.2 (Juan_esteban.xlsx): 94/94 columnas existen.
// Cada 'header' es el NOMBRE EXACTO de columna del Biody Manager (espacios/tildes/Ω/² tal cual). NO tocar.
export interface BiodyColumn { header: string; unit: string; required: boolean; }
export const BIODY_COLUMNS: Record<string, BiodyColumn> = {
  peso: { header: "Peso kg", unit: "kg", required: true },
  talla: { header: "Altura cm", unit: "cm", required: true },
  AF: { header: "Ángulo de fase a 50 kHz °", unit: "kHz", required: false },
  IR: { header: "Impedance Ratio (IR) ", unit: "", required: false },
  Re: { header: "Extracellular resistance ", unit: "", required: true },
  Ri: { header: "Intracellular resistance Ω", unit: "Ω", required: true },
  Rinf: { header: "Infinite resistance ", unit: "", required: true },
  C: { header: "Membrane capacitance nF", unit: "nF", required: true },
  Fo: { header: "Characteristic frequency kHz", unit: "kHz", required: false },
  Rc: { header: "Rcc circle center resistance ", unit: "", required: false },
  Xc: { header: "Xcc reactance of center of circle ", unit: "", required: false },
  Z5: { header: "Z5 Ohm", unit: "Ω", required: false },
  Z20: { header: "Z20 Ohm", unit: "Ω", required: false },
  Z50: { header: "Z50 Ohm", unit: "Ω", required: false },
  Z100: { header: "Z100 Ohm", unit: "Ω", required: false },
  Z200: { header: "Z200 Ohm", unit: "Ω", required: false },
  Z500: { header: "Z500 Ohm", unit: "Ω", required: false },
  R50: { header: "Resistencia a 50khz Ohm", unit: "Ω", required: false },
  imc: { header: "Body Mass Index (BMI) measurementDetails.VALEURCALCULEEEXPORT kg/m²", unit: "kg/m²", required: false },
  cintura: { header: "Patient risk monitoring Waist Size  measurementDetails.REFERENCEESTIMEEEXPORT cm", unit: "cm", required: false },
  icc: { header: "Ratio Altura/Cadera measurementDetails.VALEURCALCULEEEXPORT ", unit: "", required: false },
  ict: { header: "Ratio Cintura/Altura measurementDetails.VALEURCALCULEEEXPORT ", unit: "", required: false },
  FM: { header: "Masa grasa bruta measurementDetails.VALEURCALCULEEEXPORT kg", unit: "kg", required: true },
  FM_ref: { header: "Masa grasa bruta measurementDetails.REFERENCEESTIMEEEXPORT kg", unit: "kg", required: false },
  FM_dif: { header: "Masa grasa bruta measurementDetails.ECARTTHEORIQUEEXPORT kg", unit: "kg", required: false },
  FM_pct: { header: "Masa grasa bruta measurementDetails.VALEURCALCULEEEXPORT %", unit: "%", required: false },
  FM_pct_ref: { header: "Masa grasa bruta measurementDetails.REFERENCEESTIMEEEXPORT %", unit: "%", required: false },
  FM_hid: { header: "Masa grasa en hidratación constante measurementDetails.VALEURCALCULEEEXPORT %", unit: "%", required: false },
  FM_hid_ref: { header: "Masa grasa bruta measurementDetails.REFERENCEESTIMEEEXPORT %", unit: "%", required: false },
  FFM: { header: "Masa sin grasa measurementDetails.VALEURCALCULEEEXPORT kg", unit: "kg", required: true },
  FFM_ref: { header: "Masa sin grasa measurementDetails.REFERENCEESTIMEEEXPORT kg", unit: "kg", required: false },
  FFM_dif: { header: "Masa sin grasa measurementDetails.ECARTTHEORIQUEEXPORT kg", unit: "kg", required: false },
  FFMI: { header: "Indice de masa sin grasa (FFMI) measurementDetails.VALEURCALCULEEEXPORT kg/m²", unit: "kg/m²", required: true },
  FFMI_ref: { header: "Fat free mass index (FFMI)  Mínimo kg/m²", unit: "kg/m²", required: false },
  SMM: { header: "Masa muscular esquelética measurementDetails.VALEURCALCULEEEXPORT kg", unit: "kg", required: false },
  SMM_ref: { header: "Masa muscular esquelética measurementDetails.REFERENCEESTIMEEEXPORT kg", unit: "kg", required: false },
  SMM_dif: { header: "Masa muscular esquelética measurementDetails.ECARTTHEORIQUEEXPORT kg", unit: "kg", required: false },
  smmW: { header: "Skeletal muscle mass over weight (SMM/W) measurementDetails.VALEURCALCULEEEXPORT %", unit: "%", required: false },
  MMEM: { header: "Masa muscular esquelética de los miembros measurementDetails.VALEURCALCULEEEXPORT kg", unit: "kg", required: false },
  MMEM_ref: { header: "Masa muscular esquelética de los miembros measurementDetails.REFERENCEESTIMEEEXPORT kg", unit: "kg", required: false },
  MMEM_dif: { header: "Masa muscular esquelética de los miembros measurementDetails.ECARTTHEORIQUEEXPORT kg", unit: "kg", required: false },
  CMO: { header: "Contenido Mineral óseo measurementDetails.VALEURCALCULEEEXPORT kg", unit: "kg", required: false },
  CMO_ref: { header: "Contenido Mineral óseo measurementDetails.REFERENCEESTIMEEEXPORT kg", unit: "kg", required: false },
  CMO_dif: { header: "Contenido Mineral óseo measurementDetails.ECARTTHEORIQUEEXPORT kg", unit: "kg", required: false },
  minNoOseo: { header: "Mineral no óseo measurementDetails.VALEURCALCULEEEXPORT kg", unit: "kg", required: false },
  minNoOseo_ref: { header: "Mineral no óseo measurementDetails.REFERENCEESTIMEEEXPORT kg", unit: "kg", required: false },
  MCA: { header: "Masa celular activa measurementDetails.VALEURCALCULEEEXPORT kg", unit: "kg", required: false },
  MCA_ref: { header: "Masa celular activa measurementDetails.REFERENCEESTIMEEEXPORT kg", unit: "kg", required: false },
  MCA_dif: { header: "Masa celular activa measurementDetails.ECARTTHEORIQUEEXPORT kg", unit: "kg", required: false },
  ECM_BCM: { header: "Extracellular mass / active cell mass (ECM/BCM/ - Ratio)   measurementDetails.VALEURCALCULEEEXPORT ", unit: "", required: false },
  protTotal: { header: "Masa protéica measurementDetails.VALEURCALCULEEEXPORT kg", unit: "kg", required: false },
  protTotal_ref: { header: "Masa protéica measurementDetails.REFERENCEESTIMEEEXPORT kg", unit: "kg", required: false },
  protTotal_dif: { header: "Masa protéica measurementDetails.ECARTTHEORIQUEEXPORT kg", unit: "kg", required: false },
  protActiva: { header: "Masa protéica metabólica measurementDetails.VALEURCALCULEEEXPORT kg", unit: "kg", required: false },
  protActiva_ref: { header: "Masa protéica metabólica measurementDetails.REFERENCEESTIMEEEXPORT kg", unit: "kg", required: false },
  protActiva_dif: { header: "Masa protéica metabólica measurementDetails.ECARTTHEORIQUEEXPORT kg", unit: "kg", required: false },
  solEC: { header: "Sólidos extracelulares measurementDetails.VALEURCALCULEEEXPORT kg", unit: "kg", required: false },
  solEC_ref: { header: "Sólidos extracelulares measurementDetails.REFERENCEESTIMEEEXPORT kg", unit: "kg", required: false },
  solEC_dif: { header: "Sólidos extracelulares measurementDetails.ECARTTHEORIQUEEXPORT kg", unit: "kg", required: false },
  masaSeca: { header: "Masa seca sin grasa measurementDetails.VALEURCALCULEEEXPORT kg", unit: "kg", required: false },
  masaSeca_ref: { header: "Masa seca sin grasa measurementDetails.REFERENCEESTIMEEEXPORT kg", unit: "kg", required: false },
  masaSeca_dif: { header: "Masa seca sin grasa measurementDetails.ECARTTHEORIQUEEXPORT kg", unit: "kg", required: false },
  TBW: { header: "Agua total measurementDetails.VALEURCALCULEEEXPORT L", unit: "L", required: false },
  TBW_ref: { header: "Agua total measurementDetails.REFERENCEESTIMEEEXPORT L", unit: "L", required: false },
  TBW_dif: { header: "Hydratation de la Masse non grasse measurementDetails.ECARTTHEORIQUEEXPORT L", unit: "L", required: false },
  ECW: { header: "Extracellular water measurementDetails.VALEURCALCULEEEXPORT L", unit: "L", required: false },
  ECW_ref: { header: "Extracellular water measurementDetails.REFERENCEESTIMEEEXPORT L", unit: "L", required: false },
  ECW_dif: { header: "Extracellular water measurementDetails.ECARTTHEORIQUEEXPORT L", unit: "L", required: false },
  ECW_pct: { header: "Extracellular water measurementDetails.VALEURCALCULEEEXPORT %", unit: "%", required: false },
  ECW_pct_ref: { header: "Extracellular water measurementDetails.REFERENCEESTIMEEEXPORT %", unit: "%", required: false },
  ICW: { header: "Intracellular water (ICW) measurementDetails.VALEURCALCULEEEXPORT L", unit: "L", required: false },
  ICW_ref: { header: "Intracellular water (ICW) measurementDetails.REFERENCEESTIMEEEXPORT L", unit: "L", required: false },
  ICW_dif: { header: "Intracellular water (ICW) measurementDetails.ECARTTHEORIQUEEXPORT L", unit: "L", required: false },
  ICW_pct: { header: "Intracellular water (ICW) measurementDetails.VALEURCALCULEEEXPORT %", unit: "%", required: false },
  ICW_pct_ref: { header: "Intracellular water (ICW) measurementDetails.REFERENCEESTIMEEEXPORT %", unit: "%", required: false },
  ECW_sg: { header: "Agua extracelular sin grasa measurementDetails.VALEURCALCULEEEXPORT L", unit: "L", required: false },
  ECW_sg_ref: { header: "Agua extracelular sin grasa measurementDetails.REFERENCEESTIMEEEXPORT L", unit: "L", required: false },
  ECW_sg_pct: { header: "Agua extracelular sin grasa measurementDetails.VALEURCALCULEEEXPORT %", unit: "%", required: false },
  ECW_sg_pct_ref: { header: "Agua extracelular sin grasa measurementDetails.REFERENCEESTIMEEEXPORT %", unit: "%", required: false },
  ICW_sg: { header: "Agua intracelular sin grasa measurementDetails.VALEURCALCULEEEXPORT L", unit: "L", required: false },
  ICW_sg_ref: { header: "Agua intracelular sin grasa measurementDetails.REFERENCEESTIMEEEXPORT L", unit: "L", required: false },
  ICW_sg_dif: { header: "Agua intracelular sin grasa measurementDetails.ECARTTHEORIQUEEXPORT L", unit: "L", required: false },
  ICW_sg_pct: { header: "Agua intracelular sin grasa measurementDetails.VALEURCALCULEEEXPORT %", unit: "%", required: false },
  ICW_sg_pct_ref: { header: "Agua intracelular sin grasa measurementDetails.REFERENCEESTIMEEEXPORT %", unit: "%", required: false },
  FFW: { header: "Fat free water measurementDetails.VALEURCALCULEEEXPORT L", unit: "L", required: false },
  FFW_dif: { header: "Fat free water measurementDetails.ECARTTHEORIQUEEXPORT L", unit: "L", required: false },
  hidSG: { header: "Hidratación sin grasa measurementDetails.VALEURCALCULEEEXPORT %", unit: "%", required: false },
  hidSG_ref: { header: "Hidratación sin grasa measurementDetails.REFERENCEESTIMEEEXPORT %", unit: "%", required: false },
  ACT_MLG: { header: "Hidratación de la masa sin grasa measurementDetails.VALEURCALCULEEEXPORT %", unit: "%", required: false },
  ACT_MLG_ref: { header: "Hidratación de la masa sin grasa measurementDetails.REFERENCEESTIMEEEXPORT %", unit: "%", required: false },
  GEB: { header: "Metabolismo de base measurementDetails.VALEURCALCULEEEXPORT kcal", unit: "kcal", required: false },
  GEB_ref: { header: "Metabolismo de base measurementDetails.REFERENCEESTIMEEEXPORT kcal", unit: "kcal", required: false },
  GEB_dif: { header: "Metabolismo de base measurementDetails.ECARTTHEORIQUEEXPORT kcal", unit: "kcal", required: false },
  GET: { header: "Gasto energético measurementDetails.VALEURCALCULEEEXPORT kcal", unit: "kcal", required: false },
};

// Campo DERIVADO (no es columna): FMI = FM / (tallaM^2)  [ATLAS_v7.html L5650].
export const DERIVED_FIELDS = ['FMI'] as const;

// Insumos que el motor NÚCLEO necesita para IFC/IRC/PABU/fenotipo EFR. Faltante/fuera de rango => falla en voz alta.
export const ENGINE_REQUIRED = ['Re','Ri','Rinf','C','FM','talla','FFMI','peso'] as const;

// Insumos de los índices SECUNDARIOS (ISCM-BIS, IEHH). Opcionales: si faltan, ISCM/IEHH = null (no se inventan).
export const SECONDARY_REQUIRED = ['FFW','MCA_dif','ECW_sg','ICW_sg'] as const;
